#!/usr/bin/env python

import argparse
import uvicorn

parser = argparse.ArgumentParser()
parser.add_argument("--port", type=int, default=8888)
args = parser.parse_args()

uvicorn.run("easynlp.server:app", port=args.port)
